export const NAV_LINKS = [
  {
    label: "Home",
    to: "/",
    isPrivate: false,
  },
  {
    label: "Queries",
    to: "/queries",
    isPrivate: false,
  },
  {
    label: "Recommendations For Me",
    to: "/recommendations",
    isPrivate: true,
  },
  {
    label: "My Queries",
    to: "/my-queries",
    isPrivate: true,
  },
  {
    label: "My recommendations",
    to: "/my-recommendations",
    isPrivate: true,
  },
];

export const SLIDER_DATA = [
  {
    title: "Looking for Better Product Choices?",
    subtitle:
      "Get community-powered recommendations for smarter shopping decisions.",
    highlight: "Product",
    src: "/slide-1.png",
    btnText: "Explore Alternatives",
  },
  {
    title: "Not Sure Which Product to Pick?",
    subtitle: "Ask real users for opinions, reviews, and better suggestions.",
    highlight: "Pick?",
    src: "/slide-2.png",
    btnText: "Ask a Question",
  },
  {
    title: "Help Others Choose Right",
    subtitle:
      "Share your product recommendations to guide others just like you.",
    highlight: "Right",
    src: "/slide-3.png",
    btnText: "Add a Recommendation",
  },
];

export const dummyQueries = [
  {
    productName: "UltraSmooth Razor",
    productBrand: "ShaveCo",
    productImageURL: "https://i.ibb.co/Mx61N0tL/query-1.jpg",
    queryTitle: "Is there a better razor that offers the same smoothness?",
    boycottingReason: "Blades rust quickly and caused irritation after use.",
    currentDate: new Date("2025-05-30T14:12:43.289Z"),
    recommendationCount: 24,
  },
  {
    productName: "EcoBrew Coffee Pods",
    productBrand: "DailySip",
    productImageURL: "https://i.ibb.co/1f3scptn/query-2.jpg",
    queryTitle: "Are there more eco-friendly alternatives to this coffee pod?",
    boycottingReason: "Too much plastic packaging, not biodegradable.",
    currentDate: new Date("2025-04-25T09:34:21.587Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
  {
    productName: "SuperBass Wireless Earbuds",
    productBrand: "SoundJam",
    productImageURL: "https://i.ibb.co/M5DqrHXN/query-3.jpg",
    queryTitle: "Is there a more reliable pair with the same bass?",
    boycottingReason: "Left earbud stopped working after a week.",
    currentDate: new Date("2025-04-18T19:57:10.134Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
  {
    productName: "GlowMax LED Bulb",
    productBrand: "BrightHome",
    productImageURL: "https://i.ibb.co/yngTK76Z/query-4.jpg",
    queryTitle: "Any long-lasting LED bulbs that don’t flicker?",
    boycottingReason: "Starts flickering within a few weeks of use.",
    currentDate: new Date("2025-06-01T11:03:49.932Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
  {
    productName: "FastCharge Power Bank",
    productBrand: "VoltUp",
    productImageURL: "https://i.ibb.co/b57xrmvq/query-5.jpg",
    queryTitle: "What are better fast-charging power banks than this?",
    boycottingReason: "Claims fast-charging, but very slow in real use.",
    currentDate: new Date("2025-05-10T07:28:00.341Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
  {
    productName: "SmartChef Air Fryer",
    productBrand: "KitchenPro",
    productImageURL: "https://i.ibb.co/JR3KM80s/query-6.jpg",
    queryTitle: "Looking for better non-toxic air fryers?",
    boycottingReason: "Coating started peeling and releasing plastic smell.",
    currentDate: new Date("2025-03-29T16:15:38.478Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
  {
    productName: "AquaPure Water Filter",
    productBrand: "ClearHydro",
    productImageURL: "https://i.ibb.co/C567M6Wn/query-7.jpg",
    queryTitle: "Any reliable filters that remove fluoride too?",
    boycottingReason: "Doesn’t actually remove heavy metals as advertised.",
    currentDate: new Date("2025-05-22T20:48:59.661Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
  {
    productName: "QuickSwipe Screen Cleaner",
    productBrand: "GadgetShine",
    productImageURL: "https://i.ibb.co/D0D59yy/query-8.jpg",
    queryTitle: "Better cleaners that are safe on OLED screens?",
    boycottingReason: "Damaged screen coating on my phone.",
    currentDate: new Date("2025-04-03T13:22:05.110Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
  {
    productName: "SnuggleSoft Pillows",
    productBrand: "ComfortNest",
    productImageURL: "https://i.ibb.co/HpfgGLJf/query-9.jpg",
    queryTitle: "Is there a hypoallergenic pillow alternative?",
    boycottingReason: "Developed skin rash due to the fabric used.",
    currentDate: new Date("2025-05-17T18:10:26.901Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
  {
    productName: "FreshMint Toothpaste",
    productBrand: "SmileCare",
    productImageURL: "https://i.ibb.co/M5WG6G6N/query-10.jpg",
    queryTitle: "Any fluoride-free alternatives that still clean well?",
    boycottingReason: "Contains harsh chemicals and artificial flavors.",
    currentDate: new Date("2025-06-03T06:45:33.784Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
  {
    productName: "GripMax Mouse",
    productBrand: "ClickSmart",
    productImageURL: "https://i.ibb.co/x8MVP8Pm/query-11.jpg",
    queryTitle: "What's a better ergonomic mouse than this one?",
    boycottingReason: "Uncomfortable after long use and lags frequently.",
    currentDate: new Date("2025-04-07T12:59:50.222Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
  {
    productName: "SpeedDry Hair Dryer",
    productBrand: "StylePro",
    productImageURL: "https://i.ibb.co/rR2qSMbL/query-12.jpg",
    queryTitle: "Looking for quiet hair dryers with similar speed?",
    boycottingReason: "Very noisy and gets too hot quickly.",
    currentDate: new Date("2025-05-27T23:05:14.016Z"),
    recommendationCount: Math.round(Math.random() * 50),
  },
];
